import { HomeIcon, LayoutDashboardIcon } from "lucide-react";
import { VscOrganization } from "react-icons/vsc";
import { GoHomeFill } from "react-icons/go";
import { FaTasks, FaUsers } from "react-icons/fa";
import { LuClock } from "react-icons/lu";
import { IoChatboxOutline } from "react-icons/io5";
import { IoMdSettings } from "react-icons/io";

export const NAVBAR_LINKS = [
  {
    id: 1,
    label: "Home",
    href: "/",
    icon: HomeIcon,
  },
  {
    id: 2,
    label: "Dashboard",
    href: "/dashboard",
    icon: LayoutDashboardIcon,
  },
];

export const ADMIN_SIDEBAR_LINKS = [
  {
    id: 1,
    label: "Home",
    href: "/dashboard",
    icon: GoHomeFill,
    isDropdown: false,
  },
  {
    id: 2,
    label: "Organizations",
    href: "/dashboard/organizations",
    icon: VscOrganization,
    isDropdown: true,
  },
  {
    id: 3,
    label: "Members",
    href: "/dashboard/members",
    icon: FaUsers,
    isDropdown: false,
  },
  {
    id: 4,
    label: "Projects",
    href: "/dashboard/projects",
    icon: FaTasks,
    isDropdown: false,
  },
  {
    id: 5,
    label: "Check In/Out",
    href: "/dashboard/check-in-out",
    icon: LuClock,
    isDropdown: false,
  },
  {
    id: 6,
    label: "Chats",
    href: "/dashboard/chats",
    icon: IoChatboxOutline,
    isDropdown: false,
  },
  {
    id: 7,
    label: "Settings",
    href: "/dashboard/settings",
    icon: IoMdSettings,
    isDropdown: true,
  },
];

export const ADMIN_SETTINGS_LINKS = [
  {
    id: 1,
    label: "Checkin / Checkout",
    href: "/dashboard/checkin-checkout",
  },
  {
    id: 2,
    label: "Privacy & Security",
    href: "/dashboard/privary-and-security",
  },
  // {
  //   id: 3,
  //   label: "Appearance",
  //   href: "/dashboard/appearance",
  // },
];

export const MEMBER_SIDEBAR_LINKS = [
  {
    id: 1,
    label: "Organizations",
    href: "/dashboard/organization",
    icon: VscOrganization,
    isDropdown: true,
  },
  {
    id: 2,
    label: "Home",
    href: "/dashboard/member",
    icon: GoHomeFill,
    isDropdown: false,
  },
  {
    id: 3,
    label: "Projects",
    href: "/dashboard/member/project",
    icon: FaTasks,
    isDropdown: false,
  },
  {
    id: 4,
    label: "Check In/Out",
    href: "/dashboard/member/check-in-out",
    icon: LuClock,
    isDropdown: false,
  },
  {
    id: 5,
    label: "Chats",
    href: "/dashboard/member/chats",
    icon: IoChatboxOutline,
    isDropdown: false,
  },
  // {
  //   id: 6,
  //   label: "Settings",
  //   href: "/dashboard/member/settings",
  //   icon: IoMdSettings,
  //   isDropdown: false,
  // },
];

export const tags = [
  "graphic design",
  "web design",
  "UI/UX design",
  "animation",
  "3D modeling",
  "illustration",
  "branding",
  "logo design",
  "video editing",
  "motion graphics",
  "photography",
  "filmmaking",
  "digital art",
  "content creation",
  "copywriting",
  "blogging",
  "marketing",
  "digital marketing",
  "social media",
  "advertising",
  "SEO",
  "email marketing",
  "ecommerce",
  "dropshipping",
  "sales",
  "business development",
  "entrepreneurship",
  "startup",
  "finance",
  "investment",
  "project management",
  "product management",
  "data analysis",
  "data science",
  "machine learning",
  "artificial intelligence",
  "coding",
  "web development",
  "frontend development",
  "backend development",
  "full stack development",
  "mobile app development",
  "software engineering",
  "game development",
  "cybersecurity",
  "blockchain",
  "cloud computing",
  "devops",
  "database management",
  "networking",
  "IT support",
  "hardware",
  "UI prototyping",
  "Figma",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "After Effects",
  "Premiere Pro",
  "Canva",
  "3D animation",
  "architecture",
  "interior design",
  "fashion design",
  "music production",
  "sound design",
  "voice acting",
  "education",
  "teaching",
  "coaching",
  "public speaking",
  "writing",
  "journalism",
  "creative writing",
  "translation",
  "research",
  "psychology",
  "health",
  "fitness",
  "nutrition",
  "sports",
  "technology",
  "science",
  "space",
  "engineering",
  "mechanical design",
  "robotics",
  "automation",
  "electronics",
  "environment",
  "sustainability",
  "travel",
  "lifestyle",
  "fashion",
  "beauty",
  "photography editing",
  "influencer marketing",
  "podcasting",
  "streaming",
  "gaming",
  "AR/VR",
  "metaverse",
  "finance tech",
  "UI animation",
  "product design",
  "customer experience",
  "human resources",
  "legal",
  "real estate",
  "consulting",
  "freelancing",
  "network building",
  "branding strategy",
];

export const IPErrorMessage =
  "Your IP address is not authorized to perform this action.";
export const NoOrganization = "NO_ORGANIZATION";
