import { HomeIcon, LayoutDashboardIcon } from "lucide-react";
import { VscOrganization } from "react-icons/vsc";
import { GoHomeFill } from "react-icons/go";
import { FaTasks, FaUsers } from "react-icons/fa";
import { LuClock } from "react-icons/lu";
import { IoChatboxOutline } from "react-icons/io5";
import { IoMdSettings } from "react-icons/io";

export const NAVBAR_LINKS = [
  {
    id: 1,
    label: "Home",
    href: "/",
    icon: HomeIcon,
  },
  {
    id: 2,
    label: "Dashboard",
    href: "/dashboard",
    icon: LayoutDashboardIcon,
  },
];

export const ADMIN_SIDEBAR_LINKS = [
  {
    id: 1,
    label: "Home",
    href: "/dashboard",
    icon: GoHomeFill,
    isDropdown: false,
  },
  {
    id: 2,
    label: "Organizations",
    href: "/dashboard/organizations",
    icon: VscOrganization,
    isDropdown: true,
  },
  {
    id: 3,
    label: "Members",
    href: "/dashboard/members",
    icon: FaUsers,
    isDropdown: false,
  },
  {
    id: 4,
    label: "Projects",
    href: "/dashboard/projects",
    icon: FaTasks,
    isDropdown: false,
  },
  {
    id: 5,
    label: "Check In/Out",
    href: "/dashboard/check-in-out",
    icon: LuClock,
    isDropdown: false,
  },
  {
    id: 6,
    label: "Chats",
    href: "/dashboard/chats",
    icon: IoChatboxOutline,
    isDropdown: false,
  },
  {
    id: 7,
    label: "Settings",
    href: "/dashboard/settings",
    icon: IoMdSettings,
    isDropdown: true,
  },
];

export const ADMIN_SETTINGS_LINKS = [
  {
    id: 1,
    label: "Checkin / Checkout",
    href: "/dashboard/checkin-checkout",
  },
  {
    id: 2,
    label: "Privacy & Security",
    href: "/dashboard/privary-and-security",
  },
  // {
  //   id: 3,
  //   label: "Appearance",
  //   href: "/dashboard/appearance",
  // },
];

export const MEMBER_SIDEBAR_LINKS = [
  {
    id: 1,
    label: "Organizations",
    href: "/dashboard/organization",
    icon: VscOrganization,
    isDropdown: true,
  },
  {
    id: 2,
    label: "Home",
    href: "/dashboard/member",
    icon: GoHomeFill,
    isDropdown: false,
  },
  {
    id: 3,
    label: "Projects",
    href: "/dashboard/member/project",
    icon: FaTasks,
    isDropdown: false,
  },
  {
    id: 4,
    label: "Check In/Out",
    href: "/dashboard/member/check-in-out",
    icon: LuClock,
    isDropdown: false,
  },
  {
    id: 5,
    label: "Chats",
    href: "/dashboard/member/chats",
    icon: IoChatboxOutline,
    isDropdown: false,
  },
  // {
  //   id: 6,
  //   label: "Settings",
  //   href: "/dashboard/member/settings",
  //   icon: IoMdSettings,
  //   isDropdown: false,
  // },
];

export const tags = [
  // --- Design & Creative ---
  "graphic design",
  "web design",
  "UI/UX design",
  "product design",
  "interface design",
  "interaction design",
  "branding",
  "logo design",
  "visual identity",
  "illustration",
  "digital art",
  "concept art",
  "3D modeling",
  "3D animation",
  "motion graphics",
  "animation",
  "video editing",
  "film editing",
  "color grading",
  "photography",
  "photo editing",
  "filmmaking",
  "cinematography",
  "storyboarding",
  "typography",
  "print design",
  "package design",
  "Figma",
  "Sketch",
  "Adobe Photoshop",
  "Adobe Illustrator",
  "Premiere Pro",
  "After Effects",
  "Canva",
  "Blender",
  "Cinema 4D",
  "architecture",
  "interior design",
  "fashion design",

  // --- Content Creation ---
  "content creation",
  "copywriting",
  "content writing",
  "blogging",
  "creative writing",
  "scriptwriting",
  "technical writing",
  "journalism",
  "translation",
  "podcasting",
  "voice acting",
  "streaming",
  "YouTube",
  "TikTok",
  "TikTok editing",
  "short-form content",
  "influencer marketing",

  // --- Marketing & Business ---
  "marketing",
  "digital marketing",
  "performance marketing",
  "social media marketing",
  "advertising",
  "media buying",
  "SEO",
  "SEM",
  "email marketing",
  "content marketing",
  "growth marketing",
  "affiliate marketing",
  "brand strategy",
  "market research",
  "copywriting",
  "sales",
  "lead generation",
  "business development",
  "entrepreneurship",
  "startup",
  "freelancing",
  "consulting",
  "customer experience",
  "customer support",
  "project management",
  "product management",

  // --- E-commerce ---
  "ecommerce",
  "dropshipping",
  "Shopify",
  "Shopify development",
  "Shopify apps",
  "WooCommerce",
  "Amazon FBA",
  "Amazon PPC",
  "Amazon listing optimization",
  "Amazon seller",
  "Etsy",
  "Print on demand",
  "Walmart marketplace",
  "TikTok Shop",
  "ecommerce operations",
  "inventory management",
  "fulfillment",
  "product research",

  // --- Coding & Software Development ---
  "coding",
  "programming",
  "software engineering",
  "web development",
  "frontend development",
  "backend development",
  "full stack development",
  "mobile app development",
  "iOS development",
  "Android development",
  "game development",
  "QA testing",
  "automation testing",
  "API development",
  "API integration",
  "SaaS development",
  "SaaS startup",
  "no-code",
  "low-code",
  "bubble.io",
  "webflow",
  "wordpress",

  // --- Programming Languages ---
  "JavaScript",
  "TypeScript",
  "Python",
  "Java",
  "C++",
  "C#",
  "PHP",
  "Go",
  "Rust",
  "Swift",
  "Kotlin",
  "SQL",
  "HTML",
  "CSS",
  "React",
  "Next.js",
  "Vue",
  "Svelte",
  "Node.js",
  "Express",
  "Django",
  "Flask",
  "Laravel",
  "Spring Boot",
  "Unity",
  "Unreal Engine",

  // --- Databases ---
  "database management",
  "SQL databases",
  "NoSQL",
  "MongoDB",
  "PostgreSQL",
  "MySQL",
  "SQLite",
  "Redis",
  "Firebase",
  "database design",
  "data engineering",

  // --- AI & Data ---
  "data analysis",
  "data science",
  "machine learning",
  "deep learning",
  "artificial intelligence",
  "AI agents",
  "AI automation",
  "prompt engineering",
  "computer vision",
  "NLP",
  "data visualization",
  "analytics",
  "big data",

  // --- Cloud & DevOps ---
  "cloud computing",
  "AWS",
  "AWS Lambda",
  "AWS EC2",
  "AWS S3",
  "Azure",
  "Google Cloud",
  "cloud architecture",
  "devops",
  "CI/CD",
  "docker",
  "kubernetes",
  "linux",
  "server administration",
  "cybersecurity",
  "networking",
  "IT support",

  // --- Tech & Engineering ---
  "robotics",
  "automation",
  "IoT",
  "blockchain",
  "web3",
  "metaverse",
  "AR/VR",
  "electronics",
  "mechanical engineering",
  "electrical engineering",
  "software architecture",

  // --- Money & Finance ---
  "finance",
  "investment",
  "trading",
  "crypto",
  "fintech",
  "personal finance",
  "real estate",

  // --- Education & Personal Development ---
  "education",
  "teaching",
  "coaching",
  "public speaking",
  "psychology",
  "self-improvement",
  "career development",

  // --- Lifestyle & Misc ---
  "health",
  "fitness",
  "nutrition",
  "sports",
  "travel",
  "beauty",
  "lifestyle",
  "sustainability",
  "environment",

  // --- Work Skills ---
  "teamwork",
  "leadership",
  "time management",
  "problem solving",
  "critical thinking",
  "communication",
  "network building",
];

export const IPErrorMessage =
  "Your IP address is not authorized to perform this action.";
export const NoOrganization = "NO_ORGANIZATION";
